---
apiVersion: v1
kind: Pod
metadata:
  name: centos-worker1
  namespace: test
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "ips": [ "10.1.1.11/24" ] }
    ]'
spec:
  containers:
  - name: centos-worker1
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: multustesting-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-worker2
  namespace: test
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "ips": [ "10.1.1.12/24" ] }
    ]'
spec:
  containers:
  - name: centos-worker2
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: multustesting-worker2