---
apiVersion: v1
kind: Pod
metadata:
 name: samplepod
 annotations:
 namespace: test
   #k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
 containers:
 - name: samplepod
   command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
   image: alpine